# Numpy Arrays

In [1]:
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [7]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mymatrix = np.array(mylist)
mymatrix.shape

(3, 3)

In [10]:
mynewmatrix = np.array(mylist)

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((3,3)) + 4

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
np.ones((3,3)) * 4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
len(np.linspace(0,10,5))

5

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])