# Numpy Indexing and Selection

### Indexing Vectors

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1],arr[0]

(1, 0)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[-1]

10

In [11]:
arr[-3:]

array([ 8,  9, 10])

In [12]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [13]:
slice_arr = arr[0:4]
slice_arr

array([0, 1, 2, 3])

In [14]:
slice_arr[:] = 10
slice_arr

array([10, 10, 10, 10])

In [15]:
arr

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()
slice_arr = arr_copy
slice_arr[:] = 10

In [17]:
slice_arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [18]:
arr

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10])

### Indexing Matrix

In [20]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr_2D.shape

(3, 3)

In [24]:
arr_2D = arr_2D * 25
arr_2D

array([[ 25,  50,  75],
       [100, 125, 150],
       [175, 200, 225]])

In [25]:
arr_2D[1][1]

125

In [26]:
arr_2D[1,1]

125

In [27]:
arr_2D[:2,1:]

array([[ 50,  75],
       [125, 150]])

### Conditional Selection

In [28]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [30]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[(arr>4)&(arr<8)]

array([5, 6, 7])