# Numpy Operations

### Vectors

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [4]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [5]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [6]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
1 / arr

/home/eduardo/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [10]:
arr / arr

/home/eduardo/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
arr.sum()

55

In [13]:
arr.mean()

5.0

In [14]:
arr.max()

10

In [15]:
arr.min()

0

### Matrix

In [17]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_2D.shape

(3, 3)

In [19]:
# Sum all the values
arr_2D.sum()

45

In [22]:
# Sum all the values per row. SUM ACROSS THE ROWS
arr_2D.sum(axis=1)

array([ 6, 15, 24])

In [23]:
# Sum all the values per column. SUM ACROSS THE COLUMNS
arr_2D.sum(axis=0)

array([12, 15, 18])

In [24]:
# mean all the values per column. MEAN ACROSS THE COLUMNS
arr_2D.mean(axis=0)

array([4., 5., 6.])

In [25]:
# mean all the values per column. MEAN ACROSS THE ROWS
arr_2D.mean(axis=1)

array([2., 5., 8.])